codecs.go, datasquare.go, datasquare_test.go, extendeddatacrossword.go, extendeddatacrossword_test.go, extendeddatasquare.go, extendeddatasquare_test.go, utils.go
Introduce a `Codec` type and go fmt (hence review with "Hide whitespace changes" in the PR diff view: https://github.com/LazyLedger/rsmt2d/pull/1/files?diff=unified&w=1)
=> Type alias for codec and minor improvments

datasquare.go
=> fix incorrect error message about number of chunks required

LICENSE
=> Add Apache-2.0 license

codec_test.go, codecs.go
- Fix typo
- Use consts in switch
=> Minor clean ups

codecs.go, extendeddatacrossword.go
=> Fix enums to use iota

extendeddatacrossword_test.go
Use `i * 2` as width of each row instead of `i` (`i` is ODS width).
=> Fix repair bench to remove half from each row.

extendeddatacrossword.go, extendeddatacrossword_test.go
=> Refactor `solveCrossword` main loop to separate row and col processing

.github/workflows/ci.yml
Run CI tests with `-tags leopard`.
Note: had to remove `arm64` as a build target since cgo doesn't work with cross-compiling.
=> Test with leopard in CI

README.md, extendeddatacrossword.go, extendeddatacrossword_test.go, extendeddatasquare.go, rsmt2d_test.go
=> Make repair a method on EDS

extendeddatacrossword.go
=> Add String method for Axis.

README.md
Follow-up on a missed readme update from #93
=> Update readme to reflect removal of codec and tree

codecs.go
Is this all that was meant to close #90 ?
=> Clarifying Encode's return value in comment

datasquare.go, datasquare_test.go, extendeddatacrossword.go, tree.go
=> chore!: Revert tree.Push api to only use []byte and not also the axis

datasquare_test.go, extendeddatacrossword.go, extendeddatacrossword_test.go
Adds subtests to `extendeddatacrossword_test.go` and `datasquare_test.go` - would this already be enough to close #51 ?
=> Hierarchical tests in extendeddatacrossword_test and datasquare_test

codecs.go, extendeddatasquare.go, extendeddatasquare_test.go, infectiousRSGF8.go, leopard.go
=> feat: implementing `json.(Un)Marshaller` for `ExtendedDataSquare`

README.md
Closes https://github.com/celestiaorg/rsmt2d/issues/142
=> fix: build badge

go.mod
Closes https://github.com/celestiaorg/rsmt2d/issues/146
=> feat: upgrade to Go 1.19

NOTICE
Create NOTICE file for proper use of License
=> Add Notice file

datasquare.go
Closes https://github.com/celestiaorg/rsmt2d/issues/163
=> chore: use ErrUnevenChunks

extendeddatacrossword_test.go
Closes https://github.com/celestiaorg/rsmt2d/issues/180
=> test: remove `Axis` from tests

datasquare_test.go
Closes https://github.com/celestiaorg/rsmt2d/issues/162
=> test: fix TestLazyRootGeneration

datasquare.go, extendeddatasquare.go
Closes https://github.com/celestiaorg/rsmt2d/issues/192
=> docs: improve comments about extending

codecs.go
Closes https://github.com/celestiaorg/rsmt2d/issues/187
=> docs: fix `Decode` godoc

extendeddatacrossword.go
Closes https://github.com/celestiaorg/rsmt2d/issues/181
=> docs: godoc for rebuildShares

extendeddatacrossword.go
Closes https://github.com/celestiaorg/rsmt2d/issues/182
=> refactor: remove indexing into rebuiltExtendedShares

README.md
Closes https://github.com/celestiaorg/rsmt2d/issues/205
=> docs: fix new codec in example

.github/workflows/ci.yml, .github/workflows/lint.yml
Closes https://github.com/celestiaorg/rsmt2d/issues/160
Closes https://github.com/celestiaorg/rsmt2d/issues/223
Blocked on https://github.com/celestiaorg/rsmt2d/pull/222
=> chore: run workflows on main

README.md, rsmt2d_test.go
Closes https://github.com/celestiaorg/rsmt2d/issues/171
=> refactor: remove code duplication for flattened

extendeddatacrossword.go
Closes https://github.com/celestiaorg/rsmt2d/issues/219
=> chore: camel case preRepairSanityCheck

extendeddatasquare.go
Closes https://github.com/celestiaorg/rsmt2d/issues/243
=> chore: include edsWidth in error message

.github/dependabot.yml
Closes https://github.com/celestiaorg/rsmt2d/issues/137 Inspired by celestia-app [dependabot config](https://github.com/celestiaorg/celestia-app/blob/9ea27d47e487debe3b44dcbf74c832a5940f47a8/.github/dependabot.yml#L18-L31).
A few Go module deps need to be upgraded so I expect we'll see a few new PRs created shortly after this merges.
=> chore: enable Dependabot

extendeddatasquare_test.go
fix inconsistent function name in comment
=> docs: fix function name in comment
