celestiaorg/rsmt2d

extendeddatacrossword.go
extendeddatacrossword_test.go

Simple enough, we just have to pass a `rsmt2d.TreeConstructorFn` to `RepairExtendedDataSquare` so that we can eventually pass a nmt wrapper that is aware of hard code parity namespaces.
closes #15

Add and pass TreeConstructorFn argument to RepairExtendedDataSquare

---

datasquare.go
datasquare_test.go
extendeddatacrossword.go

this PR is a slight refactor, that adds the ability to compute the root of a single row or column. This functionality is useful repairing the square without feeding the underlying `rsmt2d.Tree` nil values when not needed.
While the current root caching mechanism is used, no attempt was made to cache individual row or column roots. This means that if any element of the square changes, then like the current implementation, each root must be recomputed. :man_shrugging:  
I'm keeping this as a draft for now, as more changes could be needed to finish [#235](https://github.com/lazyledger/lazyledger-core/pull/235)
closes #17

implement lazy root computation

---

datasquare.go
tree.go

This PR modifies the `Tree` interface to pass along the information needed to identify which cell is being pushed.
closes #19

add cell index to the Push method of Tree

---

extendeddatacrossword.go
extendeddatacrossword_test.go

I've spend some time looking into refactoring and cleaning up rsmt2d. This is the first of a few smaller PRs in this direction:
- prefix errors with `Err`
- remove tracking EDS in errors

code hygiene: idiomatic error naming

---

.github/workflows/ci.yml

We have no plans of supporting 32-bit architectures, so should use `arm64` instead of `arm`. `arm` also doesn't have `-race` checking.

CI: use arm64 instead of arm

---

.github/workflows/ci.yml

GitHub Actions don't have docker containers for ARM architectures. Remove `arm64` from test targets (but still build since we can cross-compile).

Remove arm64 from test CI

---

extendeddatacrossword_test.go

Remove 3/4 of shares for repair benchmark to test with the minimum number of shares needed.

Benchmark repair with 1/4 instead of 1/2 of shares

---

extendeddatacrossword_test.go

Fix repair to properly drop shares. It now drops exactly half from each row, to guarantee that the square can be repaired. @evan-forbes noted that there are corner cases where the square isn't repairable with <1/2 the EDS's shares (e.g. if only the first rows in their entirety are present).

Fix repair benchmark

---

README.md

Benchmarking allocations will be important with upcoming optimization attempts, so add `-benchmem` to benchmark command in readme to be clearer.

Add mem benchmark command to readme.

---

extendeddatacrossword.go
extendeddatacrossword_test.go

Fixes #25.
Optimizes repair logic to do work on a so-far correct EDS struct, and only modify it when modifications are guaranteed to not corrupt.
Note that the original implementation did a quadratic amount of work (deep copy of the entire square) each iteration, for a quadratic number of iterations (i.e. `O(n^4)`). This implementation does linear work (process a single row or column) each iteration, for a quadratic number of iterations (i.e `O(n^3)`). To my understanding, this is order-optimal.
Bench with `edsBackup` re-added as before #24 against `master` branch as of start of this PR:
```
goos: linux
goarch: amd64
pkg: github.com/lazyledger/rsmt2d
cpu: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
BenchmarkRepair/Repairing_16x16_ODS_using_RSGF8-4         	     261	   4228503 ns/op	 3644160 …
```

Return uncorrupted EDS from repair, and optimize

---

codec_test.go
codecs.go
extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go
infectiousRSGF8.go
leopard.go

This PR refactors the `Codec` api to a more typical go interface, while still maintaining separation of the leopard library using the leopard build tag. This Allows for the RSGF8 codec to be used in a thread safe fashion.

Refactor Codec API to allow for thread safe operation of the infectious RSGF8

---

extendeddatacrossword_test.go

Fix printing bug introduced in #46.

Print codec name instead of codec for repair bench

---

utils.go

Fixes #39. Refactor `flattenChunks` to only do a single allocation.
Bench before
<details>
<summary>Click to expand</summary>
```
goos: linux
goarch: amd64
pkg: github.com/lazyledger/rsmt2d
cpu: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
BenchmarkEncoding/Encoding_128_shares_using_RSGF8-4         	    5236	    210436 ns/op	   84224 B/op	     143 allocs/op
BenchmarkDecoding/Decoding_128_shares_using_RSGF8-4         	   47823	     24837 ns/op	   50552 B/op	      83 allocs/op
BenchmarkRoots/Square_Size_32x32-4                          	 1572390	       759.9 ns/op	    1536 B/op	       2 allocs/op
BenchmarkRoots/Square_Size_64x64-4                          	  769806	      1584 ns/op	    3072 B/op	       2 allocs/op
BenchmarkRoots/Square_Size_128x128-4                        	  440851	      2704 …
```

Single allocation `flattenChunks`

---

extendeddatacrossword_test.go

The repair benchmark was re-using repaired shares, resulting in only a single run of the actual repairing following by `b.N` runs of just checking that the repaired shares are correct. Fix to actually re-initialize the missing shares on each run.
Depends on #49.

Fix repair bench to re-initialize shares

---

datasquare.go
datasquare_test.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go

Implements the second choice of optimization in https://github.com/lazyledger/rsmt2d/issues/39#issuecomment-817107324. Refactoring everything to go through `Call(row, col)` would be an astronomical amount of work, as e.g. encoding libraries expect simply `[][]byte` slices. This implementation increases memory footprint by ~2 for the data square, but non-trivially reduces runtime especially at larger square sizes, as returning slices is zero-allocation.
The `Repair` benchmarks below are most representative of real-world use, and see _increasing_ decreases in runtime as square size increases.
<details>
<summary>Click to expand</summary>
```
name                                        old time/op    new time/op    delta
Encoding/Encoding_128_shares_using_RSGF8-8     144µs ± 0%     145µs ± 0% …
```

Optimization: store duplicate rows and columns

---

README.md
datasquare.go
extendeddatacrossword.go

Improve documentation

---

README.md
bit_matrix.go
bit_matrix_test.go
datasquare.go
datasquare_test.go
extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go
rsmt2d_test.go
tree.go

Partially addresses #12.
Don't export `dataSquare` methods, and instead only export `ExtendedDataSquare` methods that wrap those. Functionally mostly the same, except `Row` and `Col` now return copies, so the caller can't accidentally write to internal slices in a bad way.

Improve public API

---

extendeddatacrossword.go
extendeddatacrossword_test.go

Related to #65 
As EDS is not modified in place, then we need to return it in case of errors.

Return repaired eds in case of errors : ErrUnrepairableDataSquare,ErrByzantineRow, ErrByzantineCol

---

extendeddatacrossword.go
extendeddatacrossword_test.go

Fixes #78
Unifies `ErrByzantineRow` and `ErrByzantineCol` into `ErrByzantineRowOrCol`. Provides two helper methods `IsRow()` and `IsCol()` since negating `isRow` to figure out if something is a column isn't immediately obvious.

Unify byz row and col errors.

---

datasquare.go
extendeddatacrossword.go

`getCell` seems like another method that was supposed to become public but never got to it. I think so because it creates a copy of a chunk for encapsulation reasons, but It is only used internally now and in tests. This PR solves the problem that it avoids the use of `getCell` internally, thus avoiding copy internally, specifically in `...rangeMissingNoData`, which is just a helper func that should not do a copy for every chunk,
`getCell` won't be used anywhere after this PR is merged, so we should consider either removing it or publicizing it.

perf: check nil chunks directly to avoid copying

---

datasquare.go
extendeddatacrossword.go
extendeddatacrossword_test.go

Fixes #83
Fixes #89
Unlike the suggestion in #83 to not reset cached roots, that functionality was kept. The reason is that setting a cell from `nil` to non-`nil` does not guarantee that the roots match up with the leaves. The roots actually need to be re-computed to guarantee this, so the cache is cleared every time a cell is set.

Export `SetCell` and `GetCell`.

---

extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go
rsmt2d_test.go

Fixes #82
Interestingly, the tree func was already cached, and the passed in tree func in `Repair` was unused.

Cache codec and tree func.

---

datasquare_test.go
extendeddatasquare.go
extendeddatasquare_test.go

Closes #101. A bit overkill I guess, but doesn't hurt to have them?
@adlerjohn, Should `eds.RowRoots` and `eds.ColRoots` also return copies? If so I would add a test for those still!

testing: immutability constraints on Row, Cell, GetCell, and SetCell

---

datasquare.go
datasquare_test.go
extendeddatacrossword_test.go
extendeddatasquare.go

Opened in #97 .
Since `ImportExtendedDataSquare` takes a flattened EDS, would this export make sense? 
Would allow us to slash [`ExtractEDS`](https://github.com/celestiaorg/celestia-node/blob/7f70b9b0b25cb601070d5eee59c5482bc893032e/ipld/add.go#L83-L95
) in `celestia-node/ipld` if I'm not mistaken.

Exporting `dataSquare.flattened`

---

.github/workflows/ci.yml
go.mod

Closes https://github.com/celestiaorg/rsmt2d/issues/105
~~Draft PR until I verify that it's safe to consume a Go 1.18 module from a 1.17 app~~ See https://github.com/celestiaorg/rsmt2d/issues/105#issuecomment-1183957521

Upgrade to Go 1.18

---

extendeddatasquare_test.go

This results in more accurate extension benchmarking, computing the Merkle roots is a significant overhead.

Benchmark the root generation when benchmarking extension.

---

extendeddatacrossword.go

Before:
```
goos: linux
goarch: amd64
pkg: github.com/celestiaorg/rsmt2d
cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
BenchmarkRepair/Repairing_16x16_ODS_using_RSGF8-16         	      33	  36366217 ns/op
BenchmarkRepair/Repairing_32x32_ODS_using_RSGF8-16         	       4	 291625597 ns/op
BenchmarkRepair/Repairing_64x64_ODS_using_RSGF8-16         	       1	2196795856 ns/op
BenchmarkRepair/Repairing_128x128_ODS_using_RSGF8-16       	       1	18349927611 ns/op
```
After:
```
goos: linux
goarch: amd64
pkg: github.com/celestiaorg/rsmt2d
cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
BenchmarkRepair/Repairing_16x16_ODS_using_RSGF8-16         	     363	   3733920 ns/op
BenchmarkRepair/Repairing_32x32_ODS_using_RSGF8-16         	      82	  20524141 ns/op …
```

Crossword repair loop fixes

---

codec_test.go
datasquare_test.go
extendeddatacrossword_test.go
extendeddatasquare_test.go

- Revamps benchmarks to include separate benchmarks for extension with encoding only, and extension with both encoding and root computation
- Standardize the benchmark names
- Increase the max ODS size to 512x512
```
goos: linux
goarch: amd64
pkg: github.com/celestiaorg/rsmt2d
cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
BenchmarkEncoding/RSGF8_128_shares-16         	    8947	    132586 ns/op
BenchmarkEncoding/LeopardFF8_128_shares-16    	   10000	    103114 ns/op
BenchmarkEncoding/LeopardFF16_128_shares-16   	   12720	     92157 ns/op
BenchmarkDecoding/RSGF8_128_shares-16         	   80637	     14037 ns/op
BenchmarkDecoding/LeopardFF8_128_shares-16    	   10000	    126312 ns/op
BenchmarkDecoding/LeopardFF16_128_shares-16   	   11118	    109462 ns/op …
```

Revamp benchmarks, increase max square size

---

datasquare.go
datasquare_test.go
extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go
go.mod
go.sum
infectiousRSGF8.go
tree.go

Notes:
- although we implement some mutexes in dataSquare, we do not claim that dataSquare itself is now thread-safe, as we only added the minimal number of locks to make parallel extension work.
- in all the following benchmarks, extension has been benchmarks without computing the row and column roots, which continues to be the primary bottleneck.
- `cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz`
go-leopard + parallelisation
```
BenchmarkExtension/LeopardFF8_size_4-16         	   21063	     58295 ns/op
BenchmarkExtension/LeopardFF16_size_4-16        	   20356	     60095 ns/op
BenchmarkExtension/RSGF8_size_4-16              	   46251	     25855 ns/op
BenchmarkExtension/RSGF8_size_8-16              	   16380	     73586 ns/op
BenchmarkExtension/LeopardFF8_size_8-16         	    8278 …
```

Parallelise data extension and pre-repair sanity check

---

README.md

The build tag is not necessary after https://github.com/celestiaorg/rsmt2d/pull/136

docs: remove leopard build tag

---

extendeddatasquare.go

Resolves https://github.com/celestiaorg/celestia-app/issues/1454#issuecomment-1464360872

docs: add a note on q3

---

codecs.go

Closes https://github.com/celestiaorg/rsmt2d/issues/141

fix!: codec typo

---

extendeddatasquare.go

Closes https://github.com/celestiaorg/rsmt2d/issues/164

chore: remove unnecessary slice indexing

---

extendeddatasquare.go

Closes https://github.com/celestiaorg/rsmt2d/issues/179

refactor: improve var name

---

extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/177

refactor: consolidate conditionals

---

extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/173

docs: improve godoc for ErrByzantineData

---

extendeddatasquare.go

Closes https://github.com/celestiaorg/rsmt2d/issues/171
https://github.com/celestiaorg/rsmt2d/blob/f166196f5d9d0c8478c423f4803f0f3b18b43405/extendeddatasquare_test.go#L122-L143 still passes

chore: use deepCopy

---

datasquare.go
datasquare_test.go

Closes https://github.com/celestiaorg/rsmt2d/issues/169

chore: check width in setRowSlice and setColSlice

---

datasquare.go
datasquare_test.go

Closes https://github.com/celestiaorg/rsmt2d/issues/170
Closes https://github.com/celestiaorg/rsmt2d/issues/127
Breaking b/c modifies the function signature of a public function: `SetCell`

chore!: check newChunk size

---

codecs.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go
leopard.go

If the methods for the `Codec` interface are exported, then users can define their own interfaces outside of this package. I'm not sure if leaving the methods unexported was done on purpose, so if it was this PR can be closed.
edit: for posterity this [PR](https://github.com/celestiaorg/rsmt2d/pull/46/files) exported only a few methods, so it looks like it wasn't done on purpose, but I'm still unsure if there are any other specific reasons not to

chore!: export codec methods

---

extendeddatacrossword_test.go

Closes https://github.com/celestiaorg/rsmt2d/issues/194

refactor: improve test case names

---

extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/196
Since [`Decode`](https://github.com/rootulp/rsmt2d/blob/1f1904acc114b41dff838ad1d530feacc1d9f199/leopard.go#L46-L54) returns original + parity shares, there is no need to separately rebuild the parity shares. This PR removes an unnecessary conditional inside `rebuildShares` which let us also remove a param to that function. After the refactor, a few helper methods were no longer used so they were also removed.

refactor: simplify `rebuildShares`

---

extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/64 and motivated by https://github.com/celestiaorg/rsmt2d/issues/178#issuecomment-1601906624

docs: clarify shares inside ErrByzantineData

---

datasquare.go
datasquare_test.go
extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/202 via **Option A**
Note: this isn't breaking b/c `setCell` isn't exported.

test: do not perform input validation in `setCell`

---

.github/workflows/lint.yml
.golangci.yml
README.md
datasquare.go
datasquare_test.go
extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go
leopard.go
rsmt2d_test.go
tree.go

Closes https://github.com/celestiaorg/rsmt2d/issues/204
Marked as breaking b/c the function signature for exported functions (`RowRoots` and `ColRoots`) was modified to include an error return parameter.
1. `golangci-lint run` passes locally
2. `golangci-lint run` passes in CI [here](https://github.com/celestiaorg/rsmt2d/actions/runs/5456354873/jobs/9929053344?pr=208#step:4:27)

feat!: enable golangci-lint

---

.github/workflows/ci.yml
go.mod

Closes https://github.com/celestiaorg/rsmt2d/issues/210
I couldn't find any other occurrences of 1.18 or 1.19 in the repo.

chore: bump to Go 1.20

---

codec_test.go

Closes https://github.com/celestiaorg/rsmt2d/issues/221

chore: stop using deprecated math/rand.Read

---

codecs.go
leopard.go

Closes https://github.com/celestiaorg/rsmt2d/issues/226

docs: clarify MaxChunks applies to ODS

---

datasquare.go
datasquare_test.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go

Closes https://github.com/celestiaorg/rsmt2d/issues/231
This PR adds a new constructor called `NewExtendedDataSquare` that allows @celestia-node to explicitly set the `chunkSize` on an empty EDS. I choose to not drop the existing `ImportExtendedDataSquare` as proposed in https://github.com/celestiaorg/rsmt2d/issues/85 because that would be public API breaking. 
cc: @Wondertan @walldiss

feat: `NewExtendedDataSquare` with chunkSize param

---

extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/220

docs: clarify rowRoots to Repair

---

codecs.go
extendeddatasquare.go
extendeddatasquare_test.go
leopard.go

Closes https://github.com/celestiaorg/rsmt2d/issues/235

feat: validate chunk size is a multiple of 64 bytes

---

codec_test.go
extendeddatasquare.go
extendeddatasquare_test.go

Closes https://github.com/celestiaorg/rsmt2d/issues/234
cc: @Wondertan @walldiss

feat(eds): Flattened, FlattenedODS, Equals

---

.github/workflows/ci.yml
.github/workflows/lint.yml
README.md
go.mod
go.sum

Part of https://github.com/celestiaorg/rsmt2d/issues/161

chore: upgrade to Go 1.21

---

datasquare_test.go
extendeddatasquare.go
extendeddatasquare_test.go

close [#249](https://github.com/celestiaorg/rsmt2d/issues/249)
Add helper function and unit test for new function

feat: add roots helper function

---

extendeddatacrossword_test.go

Closed: [#216](https://github.com/celestiaorg/rsmt2d/issues/216)

test: remove test cases that vary based on codec

---

datasquare_test.go
extendeddatacrossword_test.go
extendeddatasquare_test.go
nmtwrapper_test.go

test: extends computeRoots benchmark to cover larger square sizes and nmt tree

---

codec_test.go
codecs.go
datasquare.go
datasquare_test.go
extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go
extendeddatasquare_test.go
leopard.go
rsmt2d_test.go
utils.go

Closes https://github.com/celestiaorg/rsmt2d/issues/215

refactor: chunk -> share

---

datasquare.go
extendeddatasquare.go

Protect returned shares by `Flattened()` with deepcopy similar to other exported methods

refactor: use deepCopy for eds.Flattened()

---

extendeddatasquare.go
extendeddatasquare_test.go

Corrects the bug introduced by https://github.com/celestiaorg/rsmt2d/pull/100. Currently, if `deepcopy()` encounters nil inner slice values, it creates a slice of 0 length, which is incorrect. This PR addresses the issue. The problem becomes evident when eds is partially computed, resulting in Row() or Col() methods returning invalid copies.
On the side note, it is technically breaking public API change. But the nature of the bug suggests noone relied on existing misbehaviour before.

fix: deepcopy filliing nil data with zeroes

---

datasquare.go
datasquare_test.go
extendeddatacrossword.go
extendeddatacrossword_test.go
extendeddatasquare.go

This PR standardizes index naming for rows and columns across the codebase to `rowIdx` and `colIdx`.
Resolves https://github.com/celestiaorg/rsmt2d/issues/314

refactor: make consistent names for row and col indexes

---

extendeddatacrossword.go
extendeddatacrossword_test.go
rsmt2d_test.go

The VerifyEncoding function introduced in PR #313 might not revert changes to the original row or column after successful verification. This could lead to a scenario where one of the fields, either squareRow or squareCol, retains a rebuilt share, resulting in only partial repair. This oversight would leave some repaired data unavailable when it should be accessible. Existing tests did not cover this scenario. This PR addresses the issue and includes randomized repair tests to ensure the fix is effective.

fix: verifyEncoding should revert changes in verifiable data

---

go.mod

Nothing critical, just keeping everything well ordered. As a result in the future diff will be simpler 🤷

Reorganize entries in go.mod

---

extendeddatacrossword.go

Closes https://github.com/celestiaorg/rsmt2d/issues/350
This code change is strictly for clarity and it should behave identically to before. These tests still pass:
1. https://github.com/rootulp/rsmt2d/blob/fe785dafe00a1cc6cbdd346be1bd01fd193f758e/extendeddatacrossword_test.go#L185
2. https://github.com/rootulp/rsmt2d/blob/fe785dafe00a1cc6cbdd346be1bd01fd193f758e/extendeddatacrossword_test.go#L346
cc: @odeke-em

refactor: return `byzErr` for clarity
